services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db          
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: django_user
      DB_PASSWORD: 'postgres'
      DEBUG: "True"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - django_net

volumes:
  postgres_data:

networks:
  django_net:
    driver: bridge
